version: '3.5'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: java_jsp
    volumes:
      - ./java_jsp.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/java_jsp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    volumes:
      - ./java_jsp.sql:/docker-entrypoint-initdb.d/init.sql

